apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:  
  application.properties: |
    spring.datasource.url=jdbc:postgresql://{{ .Release.Name }}-postgresql-hl:5432/mitre
    spring.datasource.username=mitre
    spring.datasource.password=mitre
    spring.security.user.name=test
    spring.security.user.password=test
    spring.kafka.bootstrap-servers={{ .Release.Name }}-kafka-headless:9092
