metadata:
  namespace: ${helm_namespace}
  labels:
    project: ${name}
    version: ${version}
spec:
  replicas: 1
  template:
    metadata:
      namespace: ${helm_namespace}
      labels:
        project: ${name}
        version: ${version}
    spec:
      volumes:
        - name: config
          configMap:
            name: ${name}-config
      containers:
        - resources:
            limits:
              memory: ${limits_memory}
            requests:
              memory: ${requests_memory}
          volumeMounts:
            - name: config
              mountPath: /app/config
