name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            ci_env=`bash <(curl -s https://codecov.io/env)`
            docker-compose --file docker-compose.test.yml run $ci_env -e CI=true -e CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}" sut
          else
            docker build . --file Dockerfile
          fi
  push:
    name: "Build and push"
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    with:
      image_name: mitre-siphon
